// Generated by CoffeeScript 1.6.3
var Agents, BasicCrud, ButtonCode, CannedResponses, Chats, Goals, Groups, LiveChatApi, OfflineMessages, Operators, PushPages, Reports, ReportsV1, Requester, Skills, Status, TrackingCode, Visitors, crypto, request,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

request = require('request');

crypto = require('crypto');

Requester = (function() {
  function Requester(user, apiKey, apiVersion, host) {
    this.user = user;
    this.apiKey = apiKey;
    this.apiVersion = apiVersion != null ? apiVersion : 2;
    this.host = host != null ? host : 'https://api.livechatinc.com/';
    this.del = __bind(this.del, this);
    this.put = __bind(this.put, this);
    this.post = __bind(this.post, this);
    this.get = __bind(this.get, this);
    this.request = request.defaults({
      auth: {
        user: this.user,
        password: this.apiKey
      },
      headers: {
        'X-API-Version': this.apiVersion
      }
    });
  }

  Requester.prototype.get = function(method, data, callback) {
    var _this = this;
    if (data == null) {
      data = {};
    }
    return this.request({
      url: this.host + method,
      qs: data
    }, function(error, response, body) {
      if (error != null) {
        return callback({
          error: error
        });
      } else {
        if (response.statusCode === 200) {
          return callback(JSON.parse(body));
        } else {
          return callback({
            error: body
          });
        }
      }
    });
  };

  Requester.prototype.post = function(method, data, callback) {
    var _this = this;
    if (data == null) {
      data = {};
    }
    return this.request.post({
      url: this.host + method,
      form: data
    }, function(error, response, body) {
      if (error != null) {
        return callback({
          error: error
        });
      } else {
        if (response.statusCode === 200) {
          return callback(JSON.parse(body));
        } else {
          return callback({
            error: body
          });
        }
      }
    });
  };

  Requester.prototype.put = function(method, data, callback) {
    var _this = this;
    if (data == null) {
      data = {};
    }
    return this.request.put({
      url: this.host + method,
      form: data
    }, function(error, response, body) {
      if (error != null) {
        return callback({
          error: error
        });
      } else {
        if (response.statusCode === 200) {
          return callback(JSON.parse(body));
        } else {
          return callback({
            error: body
          });
        }
      }
    });
  };

  Requester.prototype.del = function(method, data, callback) {
    var _this = this;
    if (data == null) {
      data = {};
    }
    return this.request.del({
      url: this.host + method,
      form: data
    }, function(error, response, body) {
      if (error != null) {
        return callback({
          error: error
        });
      } else {
        if (response.statusCode === 200) {
          return callback(JSON.parse(body));
        } else {
          return callback({
            error: body
          });
        }
      }
    });
  };

  return Requester;

})();

BasicCrud = (function() {
  function BasicCrud(api, path) {
    this.api = api;
    this.path = path;
    this["delete"] = __bind(this["delete"], this);
    this.update = __bind(this.update, this);
    this.create = __bind(this.create, this);
    this.get = __bind(this.get, this);
    this.list = __bind(this.list, this);
  }

  BasicCrud.prototype.list = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path, params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  BasicCrud.prototype.get = function(id, callback) {
    var _this = this;
    if (id == null) {
      id = '';
    }
    return this.api.get(this.path + '/' + id, {}, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  BasicCrud.prototype.create = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.post(this.path, params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  BasicCrud.prototype.update = function(id, params, callback) {
    var _this = this;
    if (id == null) {
      id = '';
    }
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.put(this.path + '/' + id, params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  BasicCrud.prototype["delete"] = function(id, callback) {
    var _this = this;
    if (id == null) {
      id = '';
    }
    return this.api.del(this.path + '/' + id, {}, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  return BasicCrud;

})();

Agents = (function(_super) {
  __extends(Agents, _super);

  function Agents(api) {
    this.api = api;
    this.resetApiKey = __bind(this.resetApiKey, this);
    Agents.__super__.constructor.call(this, this.api, 'agents');
  }

  Agents.prototype.resetApiKey = function(id, callback) {
    var _this = this;
    if (id == null) {
      id = '';
    }
    return this.api.put('agents/' + id + '/reset_api_key', {}, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  return Agents;

})(BasicCrud);

Operators = (function(_super) {
  __extends(Operators, _super);

  function Operators(api) {
    this.api = api;
    Operators.__super__.constructor.call(this, this.api, 'operators');
  }

  return Operators;

})(BasicCrud);

CannedResponses = (function(_super) {
  __extends(CannedResponses, _super);

  function CannedResponses(api) {
    this.api = api;
    CannedResponses.__super__.constructor.call(this, this.api, 'canned_responses');
  }

  return CannedResponses;

})(BasicCrud);

Chats = (function(_super) {
  __extends(Chats, _super);

  function Chats(api) {
    this.api = api;
    this.send = __bind(this.send, this);
    Chats.__super__.constructor.call(this, this.api, 'chats');
    delete this.create;
    delete this.update;
    delete this["delete"];
  }

  Chats.prototype.send = function(id, params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.post('chats/' + id + '/send_transcript', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  return Chats;

})(BasicCrud);

Goals = (function(_super) {
  __extends(Goals, _super);

  function Goals(api) {
    this.api = api;
    this.mark = __bind(this.mark, this);
    Goals.__super__.constructor.call(this, this.api, 'goals');
  }

  Goals.prototype.mark = function(id, params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.post('goals/' + id + '/mark_as_successful', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  return Goals;

})(BasicCrud);

Groups = (function(_super) {
  __extends(Groups, _super);

  function Groups(api) {
    this.api = api;
    Groups.__super__.constructor.call(this, this.api, 'groups');
  }

  return Groups;

})(BasicCrud);

OfflineMessages = (function(_super) {
  __extends(OfflineMessages, _super);

  function OfflineMessages(api) {
    this.api = api;
    OfflineMessages.__super__.constructor.call(this, this.api, 'offline_messages');
    delete this.create;
    delete this.update;
    delete this["delete"];
  }

  return OfflineMessages;

})(BasicCrud);

ReportsV1 = (function() {
  function ReportsV1(api) {
    this.api = api;
    this.getInvitationsReport = __bind(this.getInvitationsReport, this);
    this.getChatsReport = __bind(this.getChatsReport, this);
    this.path = 'reports';
  }

  ReportsV1.prototype.getChatsReport = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path + '/chats', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  ReportsV1.prototype.getInvitationsReport = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path + '/invitations', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  return ReportsV1;

})();

Reports = (function() {
  function Reports(api) {
    this.api = api;
    this.getGoalsReport = __bind(this.getGoalsReport, this);
    this.getChattingTimeReport = __bind(this.getChattingTimeReport, this);
    this.getAvailabilityReport = __bind(this.getAvailabilityReport, this);
    this.getQueueWaitingTimesReport = __bind(this.getQueueWaitingTimesReport, this);
    this.getQueuedVisitorsReport = __bind(this.getQueuedVisitorsReport, this);
    this.getRatingsRanking = __bind(this.getRatingsRanking, this);
    this.getRatingsReport = __bind(this.getRatingsReport, this);
    this.getChatsReport = __bind(this.getChatsReport, this);
    this.getDashboardDataForGroup = __bind(this.getDashboardDataForGroup, this);
    this.getDashboardDataForAgent = __bind(this.getDashboardDataForAgent, this);
    this.getDashboardData = __bind(this.getDashboardData, this);
    this.path = 'reports';
  }

  Reports.prototype.getDashboardData = function(callback) {
    var _this = this;
    return this.api.get(this.path + '/dashboard', {}, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Reports.prototype.getDashboardDataForAgent = function(id, callback) {
    var _this = this;
    return this.api.get(this.path + '/dashboard/agent/' + id, {}, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Reports.prototype.getDashboardDataForGroup = function(id, callback) {
    var _this = this;
    return this.api.get(this.path + '/dashboard/group/' + id, {}, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Reports.prototype.getChatsReport = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path + '/chats', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Reports.prototype.getRatingsReport = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path + '/ratings', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Reports.prototype.getRatingsRanking = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path + '/ratings/ranking', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Reports.prototype.getQueuedVisitorsReport = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path + '/queued_visitors', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Reports.prototype.getQueueWaitingTimesReport = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path + '/queued_visitors/waiting_times', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Reports.prototype.getAvailabilityReport = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path + '/availability', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Reports.prototype.getChattingTimeReport = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path + '/chatting_time', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Reports.prototype.getGoalsReport = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get(this.path + '/goals', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  return Reports;

})();

Status = (function() {
  function Status(api) {
    this.api = api;
    this.get = __bind(this.get, this);
  }

  Status.prototype.get = function(params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.get('status', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  return Status;

})();

Visitors = (function() {
  function Visitors(api) {
    this.api = api;
    this.addCustomVisitorDetails = __bind(this.addCustomVisitorDetails, this);
    this.listOnlyChattingVisitors = __bind(this.listOnlyChattingVisitors, this);
    this.list = __bind(this.list, this);
    this.path = 'visitors';
  }

  Visitors.prototype.list = function(callback) {
    var _this = this;
    return this.api.get(this.path, {}, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Visitors.prototype.listOnlyChattingVisitors = function(callback) {
    var _this = this;
    return this.api.get(this.path + '/chatting', {}, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  Visitors.prototype.addCustomVisitorDetails = function(id, params, callback) {
    var _this = this;
    if (params == null) {
      params = {};
    }
    if (typeof params === 'function' && (callback == null)) {
      callback = params;
      params = {};
    }
    return this.api.post(this.path + '/' + id + '/details', params, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  return Visitors;

})();

Skills = (function(_super) {
  __extends(Skills, _super);

  function Skills(api) {
    this.api = api;
    Skills.__super__.constructor.call(this, this.api, 'skills');
  }

  return Skills;

})(BasicCrud);

PushPages = (function(_super) {
  __extends(PushPages, _super);

  function PushPages(api) {
    this.api = api;
    PushPages.__super__.constructor.call(this, this.api, 'push_pages');
  }

  return PushPages;

})(BasicCrud);

TrackingCode = (function() {
  function TrackingCode(api) {
    this.api = api;
    this.get = __bind(this.get, this);
    this.path = 'tracking_code';
  }

  TrackingCode.prototype.get = function(callback) {
    var _this = this;
    return this.api.get(this.path + '/', {}, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  return TrackingCode;

})();

ButtonCode = (function() {
  function ButtonCode(api) {
    this.api = api;
    this.get = __bind(this.get, this);
    this.path = 'button_code';
  }

  ButtonCode.prototype.get = function(callback) {
    var _this = this;
    return this.api.get(this.path + '/', {}, function(response) {
      if (callback != null) {
        return callback(response);
      }
    });
  };

  return ButtonCode;

})();

LiveChatApi = (function(_super) {
  __extends(LiveChatApi, _super);

  function LiveChatApi(user, apiKey, apiVersion) {
    this.user = user;
    this.apiKey = apiKey;
    this.apiVersion = apiVersion != null ? apiVersion : 2;
    LiveChatApi.__super__.constructor.call(this, this.user, this.apiKey, this.apiVersion);
    if (this.apiVersion === 2) {
      this.agents = new Agent(this);
      this.groups = new Groups(this);
      this.reports = new Reports(this)(this(2));
    } else if (this.apiVersion === 1) {
      this.operators = new Operators(this);
      this.offline_messages = new OfflineMessages(this);
      this.skills = new Skills(this);
      this.push_pages = new PushPages(this);
      this.tracking_code = new TrackingCode(this);
      this.button_code = new ButtonCode(this);
      this.reports = new ReportsV1(this);
    }
    this.canned_responses = new CannedResponses(this);
    this.chats = new Chats(this);
    this.goals = new Goals(this);
    this.status = new Status(this);
    this.visitors = new Visitors(this);
  }

  return LiveChatApi;

})(Requester);

exports.LiveChatApi = LiveChatApi;
